name: "MQTT IO Servo Control"
version: "1.0.0"
slug: "mqtt_io_servo"
description: "MQTT IO for servo control on GPIO"
arch:
- armhf
- armv7
startup: services
boot: auto
host_network: true
devices:
- /dev/gpiochip0
- /dev/gpiochip1
map:
- config:rw